# Note that it is recommended to utilize .config/docker-compose-base.yaml,
#   but we choose not to because we want to do things in a more custom way.
services:
  grafana:
    container_name: 'grafana-dev-wildgraphql'
    platform: 'linux/amd64'
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-11.6.14}
        development: 'true'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
        reservations:
          cpus: '0.75'
          memory: 256M
    volumes:
      - ./provisioned-dashboards:/provisioned-dashboards:ro
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
  graphql-echo:
    container_name: 'grafana-dev-wildgraphql-graphql-echo'
#   image: 'ghcr.io/retrodaredevil/graphql-echo:0.1'
    image: 'ghcr.io/retrodaredevil/graphql-echo:sha-b1c6835'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
        reservations:
          cpus: '0.75'
          memory: 256M
