{
 "title": "Wild Mountain Farms SolarThing",
 "tags": [ "SolarThing" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data source",
    "query": "retrodaredevil-wildgraphql-datasource"
   },
   { "name": "sourceId", "label": "Source ID", "query": "default,cabin" }
  ]
 },
 "panels": [
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "queryStatusLast.batteryVoltageAverage",
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  queryStatusLast(sourceId: $sourceId, to: $to) {\n    batteryVoltageAverage {\n      dateMillis\n      data\n    }\n  }\n}\n",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Temperature Data",
   "type": "stat",
   "description": "A reading of temperatures. \n\nNote that the values displayed here are not affected by the currently selected Source ID",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.temperature",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "UNKNOWN",
          "required": false
         },
         "name": "displayName",
         "type": "field",
         "value": "meta.name"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifierRepresentation",
         "type": "field",
         "value": "packet.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      },
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        { "name": "displayName", "type": "constant", "value": "Battery" },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifierRepresentation",
         "type": "field",
         "value": "packet.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  data: queryStatusLast(sourceId: $sourceId, to: $to) {\n    temperature {\n      dateMillis\n      fragmentIdString\n      packet {\n        temperatureFahrenheit\n        identifier {\n          representation\n        }\n      }\n      meta {\n        name\n      }\n    }\n    roverStatus {\n      dateMillis\n      fragmentIdString\n      packet {\n        batteryTemperatureFahrenheit\n        identifier {\n          representation\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"default\"\n}"
    }
   ]
  },
  {
   "title": "PV Wattage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.solar",
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  data: queryStatusLast(to: $to, sourceId: $sourceId) {\n    solar {\n      dateMillis\n      packet {\n        pvWattage\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.fxStatus",
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  data: queryStatusLast(to: $to, sourceId: $sourceId) {\n    fxStatus {\n      dateMillis\n      packet {\n        powerUsageWattage\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Daily kWh",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.data",
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  data:queryFullDay(from:$to, to:$to, sourceId:$sourceId) {\n    data:singleDailyKWH {\n      dateMillis\n      data\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "operationName": "BatteryVoltage",
     "parsingOptions": [
      {
       "dataPath": "queryStatus.batteryVoltage",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "packet.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query BatteryVoltage($sourceId: String!, $from: Long!, $to: Long!) {\n  queryStatus(sourceId: $sourceId, from: $from, to: $to) {\n    batteryVoltage {\n      dateMillis\n      fragmentIdString\n      packet {\n        batteryVoltage\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}\n",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "PV Wattage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.solar",
       "labelOptions": [
        {
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        },
        { "name": "fragmentId", "type": "field", "value": "fragmentIdString" }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  data: queryStatusLast(to: $to, sourceId: $sourceId) {\n    solar {\n      dateMillis\n      fragmentIdString\n      packet {\n        pvWattage\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Device Mode",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.solarDevice",
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  data: queryStatusLast(to: $to, sourceId: $sourceId) {\n    solarDevice {\n      packet {\n        identityInfo {\n          displayName\n        }\n        modeName: solarModeTypeDisplayName\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Solcast kWh Forecasts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "today.data",
       "labelOptions": [
        { "name": "displayName", "type": "constant", "value": "Today's Forecast" }
       ],
       "timeFields": [
        { "timePath": "dayStart" }
       ]
      },
      {
       "dataPath": "tomorrow.data",
       "labelOptions": [
        { "name": "displayName", "type": "constant", "value": "Tomorrow's Forecast" }
       ],
       "timeFields": [
        { "timePath": "dayStart" }
       ]
      },
      {
       "dataPath": "dayAfterTomorrow.data",
       "labelOptions": [
        { "name": "displayName", "type": "constant", "value": "Day After Tommorrow's Forecast" }
       ],
       "timeFields": [
        { "timePath": "dayStart" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  today: querySolcastDay(to: $to, sourceId: $sourceId) {\n    data: queryEnergyEstimate {\n      dayStart\n      dailyKWH\n    }\n  }\n  tomorrow: querySolcastDay(to: $to, sourceId: $sourceId) {\n    data: queryEnergyEstimate(offset: 1) {\n      dayStart\n      dailyKWH\n    }\n  }\n  dayAfterTomorrow: querySolcastDay(to: $to, sourceId: $sourceId) {\n    data: queryEnergyEstimate(offset: 2) {\n      dayStart\n      dailyKWH\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Magical Battery Voltage *",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.data",
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  data: queryBatteryEstimate(to: $to, duration: \"PT24H\", sourceId: $sourceId) {\n    data: queryEstimate(ratio: 0.3333) {\n      dateMillis\n      data\n      identifiable {\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "PV Wattage",
   "type": "timeseries",
   "description": "The wattage as measured to the input of the charge controllers\n\nTODO: Add solcast forcast",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "operationName": "BatteryVoltage",
     "parsingOptions": [
      {
       "dataPath": "queryStatus.solar",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "packet.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      },
      {
       "dataPath": "queryStatus.flatData",
       "labelOptions": [
        { "name": "displayName", "type": "constant", "value": "Total" }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query BatteryVoltage($sourceId: String!, $from: Long!, $to: Long!) {\n  queryStatus(sourceId: $sourceId, from: $from, to: $to) {\n    solar {\n      dateMillis\n      fragmentIdString\n      packet {\n        pvWattage\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n    flatData {\n      dateMillis\n      data {\n        chargeController {\n          pvWattage\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "queryStatus.temperature",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "UNKNOWN",
          "required": false
         },
         "name": "metaName",
         "type": "field",
         "value": "meta.name"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "dataId",
         "type": "field",
         "value": "packet.dataIdString"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  queryStatus(from: $from, to: $to) {\n    temperature {\n      dateMillis\n      fragmentIdString\n      packet {\n        temperatureFahrenheit\n        dataIdString\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n      meta {\n        name\n      }\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "Power Usage (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "queryStatus.fxStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "packet.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $from: Long!, $to: Long!) {\n  queryStatus(sourceId: $sourceId, from: $from, to: $to) {\n    fxStatus {\n      dateMillis\n      fragmentIdString\n      packet {\n        powerUsageWattage\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Daily kWh",
   "type": "timeseries",
   "description": "A graph of the energy produced by the solar panels. These values reset at the end of the day.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "operationName": "dailyKWHQuery",
     "parsingOptions": [
      {
       "dataPath": "data.data",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "identifiable.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "identifiable.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      },
      {
       "dataPath": "data.sum",
       "labelOptions": [
        { "name": "displayName", "type": "constant", "value": "Total" }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query dailyKWHQuery($sourceId: String!, $from: Long!, $to: Long!) {\n  data: queryFullDay(from: $from, to: $to, sourceId: $sourceId) {\n    data: dailyKWH {\n      dateMillis\n      data\n      fragmentIdString\n      identifiable {\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n    sum:dailyKWHSum {\n      dateMillis\n      data\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Load on Battery (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "queryStatus.fxStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "packet.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $from: Long!, $to: Long!) {\n  queryStatus(sourceId: $sourceId, from: $from, to: $to) {\n    fxStatus {\n      dateMillis\n      fragmentIdString\n      packet {\n        inverterWattage\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Generator Charging (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "operationName": "GeneratorChargingQuery",
     "parsingOptions": [
      {
       "dataPath": "queryStatus.fxStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "packet.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query GeneratorChargingQuery($sourceId: String!, $from: Long!, $to: Long!) {\n  queryStatus(sourceId: $sourceId, from: $from, to: $to) {\n    fxStatus {\n      dateMillis\n      fragmentIdString\n      packet {\n        chargerWattage\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Energy used over time (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "queryStatus.fxDaily",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "packet.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!, $from: Long!, $to: Long!) {\n  queryStatus(from: $from, to: $to, sourceId: $sourceId) {\n    fxDaily {\n      dateMillis\n      fragmentIdString\n      packet {\n        inverterKWH\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Generator Buying (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "operationName": "GeneratorBuyingQuery",
     "parsingOptions": [
      {
       "dataPath": "queryStatus.fxStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "packet.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query GeneratorBuyingQuery($sourceId: String!, $from: Long!, $to: Long!) {\n  queryStatus(sourceId: $sourceId, from: $from, to: $to) {\n    fxStatus {\n      dateMillis\n      fragmentIdString\n      packet {\n        buyWattage\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "queryStatus.cpuTemperature",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "UNKNOWN",
          "required": false
         },
         "name": "deviceName",
         "type": "field",
         "value": "fragmentDeviceInfo.deviceName"
        },
        { "name": "suffix", "type": "constant", "value": "CPU" }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      },
      {
       "dataPath": "queryStatus.roverBattery",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "deviceName",
         "type": "field",
         "value": "packet.identityInfo.name"
        },
        { "name": "suffix", "type": "constant", "value": "Battery" }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      },
      {
       "dataPath": "queryStatus.roverController",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "deviceName",
         "type": "field",
         "value": "packet.identityInfo.name"
        },
        { "name": "suffix", "type": "constant", "value": "Internal" }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      },
      {
       "dataPath": "queryStatus.tracerBattery",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "deviceName",
         "type": "field",
         "value": "packet.identityInfo.name"
        },
        { "name": "suffix", "type": "constant", "value": "Battery" }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      },
      {
       "dataPath": "queryStatus.tracerController",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "deviceName",
         "type": "field",
         "value": "packet.identityInfo.name"
        },
        { "name": "suffix", "type": "constant", "value": "Internal" }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  queryStatus(from: $from, to: $to) {\n    cpuTemperature {\n      dateMillis\n      fragmentIdString\n      packet {\n        cpuTemperatureFahrenheit\n      }\n      fragmentDeviceInfo {\n        deviceName\n      }\n    }\n    roverBattery: roverStatus {\n      dateMillis\n      fragmentIdString\n      packet {\n        batteryTemperatureFahrenheit\n        identifier {\n          representation\n        }\n        identityInfo {\n          name\n        }\n      }\n    }\n    roverController: roverStatus {\n      dateMillis\n      fragmentIdString\n      packet {\n        controllerTemperatureFahrenheit\n        identifier {\n          representation\n        }\n        identityInfo {\n          name\n        }\n      }\n    }\n    tracerBattery: tracerStatus {\n      dateMillis\n      fragmentIdString\n      packet {\n        batteryTemperatureFahrenheit\n        identifier {\n          representation\n        }\n        identityInfo {\n          name\n        }\n      }\n    }\n    tracerController: tracerStatus {\n      dateMillis\n      fragmentIdString\n      packet {\n        controllerTemperatureFahrenheit\n        identifier {\n          representation\n        }\n        identityInfo {\n          name\n        }\n      }\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "Average Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "operationName": "BatteryVoltage",
     "parsingOptions": [
      {
       "dataPath": "queryBatteryRecord.averageBatteryVoltage",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "identifiable.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "identifiable.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query BatteryVoltage($sourceId: String!, $from: Long!, $to: Long!) {\n  queryBatteryRecord(from: $from, to: $to, sourceId: $sourceId) {\n    averageBatteryVoltage {\n      dateMillis\n      data\n      fragmentIdString\n      identifiable {\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Scheduled Commands",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "queryAlter.scheduledCommands",
       "timeFields": [
        { "timePath": "data.scheduledTimeMillis" }
       ]
      }
     ],
     "queryText": "query ($sourceId: String!) {\n  queryAlter(sourceId: $sourceId) {\n    scheduledCommands {\n      data {\n        scheduledTimeMillis\n        commandName\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Battery Voltage Temperature Compensated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "operationName": "BatteryVoltage",
     "parsingOptions": [
      {
       "dataPath": "queryStatus.batteryVoltageTemperatureCompensated",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "identifiable.identityInfo.displayName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "fragmentId",
         "type": "field",
         "value": "fragmentIdString"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "identifier",
         "type": "field",
         "value": "identifiable.identifier.representation"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query BatteryVoltage($sourceId: String!, $from: Long!, $to: Long!) {\n  queryStatus(sourceId: $sourceId, from: $from, to: $to) {\n    batteryVoltageTemperatureCompensated {\n      dateMillis\n      fragmentIdString\n      data\n      identifiable {\n        identifier {\n          representation\n        }\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}\n",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Active Flags",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "queryAlter.activeFlags",
       "timeFields": []
      }
     ],
     "queryText": "query ($sourceId: String!, $to: Long!) {\n  queryAlter(sourceId: $sourceId) {\n    activeFlags(dateMillis: $to) {\n      flagData {\n        flagName\n      }\n    }\n  }\n}",
     "variables": "{\n  \"sourceId\": \"$sourceId\"\n}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "queryFXCharging",
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  queryFXCharging(from: $from, to: $to, fragmentId: 1) {\n    dateMillis\n    data {\n      remainingAbsorbTimeMillis\n      remainingFloatTimeMillis\n      remainingEqualizeTimeMillis\n    }\n  }\n}"
    }
   ]
  }
 ]
}