{
 "title": "Star Wars Film Info",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data source",
    "query": "retrodaredevil-wildgraphql-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Film Information",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "parsingOptions": [
      { "dataPath": "allFilms.films" }
     ],
     "queryText": "query {\n  allFilms {\n    films {\n      Title:title\n      Directory:director\n      Release:releaseDate\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "A New Hope Opening Crawl",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "parsingOptions": [
      { "dataPath": "film" }
     ],
     "queryText": "query {film(id: \"ZmlsbXM6MQ==\") {openingCrawl}}\n"
    }
   ]
  },
  {
   "title": "Database Activity December 2014",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "allFilms.films",
       "timeFields": [
        { "timePath": "created" }
       ]
      }
     ],
     "queryText": "query {\n  allFilms {\n    films {\n      Title:title\n      episodeID\n      created\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Most Populus Planets",
   "type": "barchart",
   "description": "This shows the populations of different planets. It is also a great test to understand what happens when the GraphQL response emits null values. Wild GraphQL datasource currently has logic to remove any entry with a null value in one of its fields.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "People" } },
   "targets": [
    {
     "parsingOptions": [
      { "dataPath": "allPlanets.planets" }
     ],
     "queryText": "query {\n  allPlanets {\n    planets {\n      name\n      population\n      gravity\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Starships",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "parsingOptions": [
      { "dataPath": "allStarships.starships" }
     ],
     "queryText": "query {\n  allStarships {\n    starships {\n      name\n      passengers\n      filmConnection {\n        totalCount\n      }\n    }\n  }\n}\n"
    }
   ]
  }
 ]
}